name: Install Dependencies

on: [push, workflow_dispatch]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Commit package-lock.json
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         git config --global user.name 'github-actions'
         git config --global user.email 'github-actions@github.com'
         git add package-lock.json
         git commit -m "Installed dependencies via GitHub Actions" || echo "No changes to commit"
         git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/NotReal003/Requests.git main
